# Generated by Django 5.2.1 on 2025-05-26 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='study_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.course'),
        ),
    ]
