# Generated by Django 5.2.1 on 2025-05-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studygroup_members_alter_studygroup_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
