# Generated by Django 5.2.1 on 2025-05-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studygroup_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
