# Generated by Django 5.2.1 on 2025-05-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupmembership_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
