# Generated by Django 5.2.1 on 2025-05-27 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studygroup_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('user', 'group')},
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='status',
        ),
    ]
